name: Continuos Integration

on:
  pull_request:
jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Usinga Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: run install, build 
        run: |
          npm install
          npm run build